cloneBasePath: fakerepos
repositories:
  - remoteUrl: git@github.com:rauljordan/testingrepo.git
    remoteName: testingrepo
    mirrorUrl: git@github.com:rauljordan/testingmirror.git
    mirrorName: testingmirror
    mirrorDirectories:
      - proto/eth